apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-frontend
  template:
    metadata:
      labels:
        app: todolist-frontend
    spec:
      containers:
      - name: todolist-frontend
        image: alinazim363/todolist-frontend:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: TODO_API_URL
          value: "http://34.29.150.16:5001"
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: todolist-frontend
  ports:
  - protocol: TCP
    port: 80       
    targetPort: 5002  


